import { Lang } from '../types';

/**
 * Section headings, table column headers, and short string literals surfaced
 * in the SSR body of service detail, services index, and content pages.
 *
 * Root cause for Issue 2 in the 2026-04-24 audit: service_pages has no
 * `sections` jsonb, so the renderer places an H2 above each fixed column
 * (capabilities, materials, tolerances, …). Those H2 strings plus the table
 * column headers and "Step N:" prefixes were English literals in the
 * renderer, meaning every non-EN service page emitted English section
 * headings above otherwise-localized body text.
 *
 * Translations mirror the terminology used in the DB-seeded body copy for
 * each language (Werkstoffe / Toleranzen / Ablauf for DE, Matériaux /
 * Tolérances / Déroulement for FR, etc.). English terms that stay the same
 * cross-language — CNC, STEP, ISO — are preserved in the DB body and not
 * touched here.
 */
export interface ServicePageLabels {
  capabilities: string;
  materials: string;
  materialHeader: string;
  gradeHeader: string;
  propertiesHeader: string;
  commonUsesHeader: string;
  tolerances: string;
  specHeader: string;
  valueHeader: string;
  notesHeader: string;
  howItWorks: string;
  step: string;
  leadTimes: string;
  tierHeader: string;
  quantityHeader: string;
  workingDaysHeader: string;
  applications: string;
  whyMicronsHub: string;
  faq: string;
  relatedServices: string;
}

const EN: ServicePageLabels = {
  capabilities: 'Capabilities',
  materials: 'Materials',
  materialHeader: 'Material',
  gradeHeader: 'Grade',
  propertiesHeader: 'Properties',
  commonUsesHeader: 'Common Uses',
  tolerances: 'Tolerances & Specifications',
  specHeader: 'Spec',
  valueHeader: 'Value',
  notesHeader: 'Notes',
  howItWorks: 'How It Works',
  step: 'Step',
  leadTimes: 'Lead Times',
  tierHeader: 'Tier',
  quantityHeader: 'Quantity',
  workingDaysHeader: 'Working Days',
  applications: 'Applications',
  whyMicronsHub: 'Why Microns Hub',
  faq: 'Frequently Asked Questions',
  relatedServices: 'Related Services',
};

export const SERVICE_PAGE_LABELS: Record<Lang, ServicePageLabels> = {
  en: EN,
  de: {
    capabilities: 'Leistungsumfang',
    materials: 'Werkstoffe',
    materialHeader: 'Werkstoff',
    gradeHeader: 'Güte',
    propertiesHeader: 'Eigenschaften',
    commonUsesHeader: 'Typische Anwendungen',
    tolerances: 'Toleranzen & Spezifikationen',
    specHeader: 'Merkmal',
    valueHeader: 'Wert',
    notesHeader: 'Hinweise',
    howItWorks: 'Ablauf',
    step: 'Schritt',
    leadTimes: 'Lieferzeiten',
    tierHeader: 'Stufe',
    quantityHeader: 'Stückzahl',
    workingDaysHeader: 'Arbeitstage',
    applications: 'Anwendungen',
    whyMicronsHub: 'Warum Microns Hub',
    faq: 'Häufig gestellte Fragen',
    relatedServices: 'Verwandte Leistungen',
  },
  fr: {
    capabilities: 'Capacités',
    materials: 'Matériaux',
    materialHeader: 'Matériau',
    gradeHeader: 'Nuance',
    propertiesHeader: 'Propriétés',
    commonUsesHeader: 'Usages courants',
    tolerances: 'Tolérances et spécifications',
    specHeader: 'Paramètre',
    valueHeader: 'Valeur',
    notesHeader: 'Remarques',
    howItWorks: 'Déroulement',
    step: 'Étape',
    leadTimes: 'Délais de livraison',
    tierHeader: 'Niveau',
    quantityHeader: 'Quantité',
    workingDaysHeader: 'Jours ouvrés',
    applications: 'Applications',
    whyMicronsHub: 'Pourquoi Microns Hub',
    faq: 'Questions fréquentes',
    relatedServices: 'Services associés',
  },
  es: {
    capabilities: 'Capacidades',
    materials: 'Materiales',
    materialHeader: 'Material',
    gradeHeader: 'Grado',
    propertiesHeader: 'Propiedades',
    commonUsesHeader: 'Usos comunes',
    tolerances: 'Tolerancias y especificaciones',
    specHeader: 'Especificación',
    valueHeader: 'Valor',
    notesHeader: 'Notas',
    howItWorks: 'Cómo funciona',
    step: 'Paso',
    leadTimes: 'Plazos de entrega',
    tierHeader: 'Nivel',
    quantityHeader: 'Cantidad',
    workingDaysHeader: 'Días laborables',
    applications: 'Aplicaciones',
    whyMicronsHub: 'Por qué Microns Hub',
    faq: 'Preguntas frecuentes',
    relatedServices: 'Servicios relacionados',
  },
  it: {
    capabilities: 'Capacità',
    materials: 'Materiali',
    materialHeader: 'Materiale',
    gradeHeader: 'Grado',
    propertiesHeader: 'Proprietà',
    commonUsesHeader: 'Usi comuni',
    tolerances: 'Tolleranze e specifiche',
    specHeader: 'Specifica',
    valueHeader: 'Valore',
    notesHeader: 'Note',
    howItWorks: 'Come funziona',
    step: 'Fase',
    leadTimes: 'Tempi di consegna',
    tierHeader: 'Livello',
    quantityHeader: 'Quantità',
    workingDaysHeader: 'Giorni lavorativi',
    applications: 'Applicazioni',
    whyMicronsHub: 'Perché Microns Hub',
    faq: 'Domande frequenti',
    relatedServices: 'Servizi correlati',
  },
  nl: {
    capabilities: 'Mogelijkheden',
    materials: 'Materialen',
    materialHeader: 'Materiaal',
    gradeHeader: 'Kwaliteit',
    propertiesHeader: 'Eigenschappen',
    commonUsesHeader: 'Veelvoorkomende toepassingen',
    tolerances: 'Toleranties en specificaties',
    specHeader: 'Specificatie',
    valueHeader: 'Waarde',
    notesHeader: 'Opmerkingen',
    howItWorks: 'Hoe het werkt',
    step: 'Stap',
    leadTimes: 'Levertijden',
    tierHeader: 'Niveau',
    quantityHeader: 'Aantal',
    workingDaysHeader: 'Werkdagen',
    applications: 'Toepassingen',
    whyMicronsHub: 'Waarom Microns Hub',
    faq: 'Veelgestelde vragen',
    relatedServices: 'Gerelateerde diensten',
  },
  pl: {
    capabilities: 'Możliwości',
    materials: 'Materiały',
    materialHeader: 'Materiał',
    gradeHeader: 'Gatunek',
    propertiesHeader: 'Właściwości',
    commonUsesHeader: 'Typowe zastosowania',
    tolerances: 'Tolerancje i specyfikacje',
    specHeader: 'Parametr',
    valueHeader: 'Wartość',
    notesHeader: 'Uwagi',
    howItWorks: 'Jak to działa',
    step: 'Krok',
    leadTimes: 'Czasy realizacji',
    tierHeader: 'Poziom',
    quantityHeader: 'Ilość',
    workingDaysHeader: 'Dni robocze',
    applications: 'Zastosowania',
    whyMicronsHub: 'Dlaczego Microns Hub',
    faq: 'Najczęściej zadawane pytania',
    relatedServices: 'Powiązane usługi',
  },
  pt: {
    capabilities: 'Capacidades',
    materials: 'Materiais',
    materialHeader: 'Material',
    gradeHeader: 'Grau',
    propertiesHeader: 'Propriedades',
    commonUsesHeader: 'Usos comuns',
    tolerances: 'Tolerâncias e especificações',
    specHeader: 'Especificação',
    valueHeader: 'Valor',
    notesHeader: 'Notas',
    howItWorks: 'Como funciona',
    step: 'Etapa',
    leadTimes: 'Prazos de entrega',
    tierHeader: 'Nível',
    quantityHeader: 'Quantidade',
    workingDaysHeader: 'Dias úteis',
    applications: 'Aplicações',
    whyMicronsHub: 'Por que Microns Hub',
    faq: 'Perguntas frequentes',
    relatedServices: 'Serviços relacionados',
  },
  sv: {
    capabilities: 'Kapacitet',
    materials: 'Material',
    materialHeader: 'Material',
    gradeHeader: 'Kvalitet',
    propertiesHeader: 'Egenskaper',
    commonUsesHeader: 'Vanliga användningsområden',
    tolerances: 'Toleranser och specifikationer',
    specHeader: 'Specifikation',
    valueHeader: 'Värde',
    notesHeader: 'Anmärkningar',
    howItWorks: 'Så fungerar det',
    step: 'Steg',
    leadTimes: 'Leveranstider',
    tierHeader: 'Nivå',
    quantityHeader: 'Antal',
    workingDaysHeader: 'Arbetsdagar',
    applications: 'Tillämpningar',
    whyMicronsHub: 'Varför Microns Hub',
    faq: 'Vanliga frågor',
    relatedServices: 'Relaterade tjänster',
  },
  da: {
    capabilities: 'Kapacitet',
    materials: 'Materialer',
    materialHeader: 'Materiale',
    gradeHeader: 'Kvalitet',
    propertiesHeader: 'Egenskaber',
    commonUsesHeader: 'Almindelige anvendelser',
    tolerances: 'Tolerancer og specifikationer',
    specHeader: 'Specifikation',
    valueHeader: 'Værdi',
    notesHeader: 'Bemærkninger',
    howItWorks: 'Sådan fungerer det',
    step: 'Trin',
    leadTimes: 'Leveringstider',
    tierHeader: 'Niveau',
    quantityHeader: 'Antal',
    workingDaysHeader: 'Arbejdsdage',
    applications: 'Anvendelser',
    whyMicronsHub: 'Hvorfor Microns Hub',
    faq: 'Ofte stillede spørgsmål',
    relatedServices: 'Relaterede tjenester',
  },
  fi: {
    capabilities: 'Valmiudet',
    materials: 'Materiaalit',
    materialHeader: 'Materiaali',
    gradeHeader: 'Laatu',
    propertiesHeader: 'Ominaisuudet',
    commonUsesHeader: 'Tyypilliset käyttökohteet',
    tolerances: 'Toleranssit ja spesifikaatiot',
    specHeader: 'Erittely',
    valueHeader: 'Arvo',
    notesHeader: 'Huomautukset',
    howItWorks: 'Näin se toimii',
    step: 'Vaihe',
    leadTimes: 'Toimitusajat',
    tierHeader: 'Taso',
    quantityHeader: 'Määrä',
    workingDaysHeader: 'Työpäivää',
    applications: 'Sovellukset',
    whyMicronsHub: 'Miksi Microns Hub',
    faq: 'Usein kysytyt kysymykset',
    relatedServices: 'Liittyvät palvelut',
  },
  nb: {
    capabilities: 'Kapasitet',
    materials: 'Materialer',
    materialHeader: 'Materiale',
    gradeHeader: 'Kvalitet',
    propertiesHeader: 'Egenskaper',
    commonUsesHeader: 'Vanlige bruksområder',
    tolerances: 'Toleranser og spesifikasjoner',
    specHeader: 'Spesifikasjon',
    valueHeader: 'Verdi',
    notesHeader: 'Merknader',
    howItWorks: 'Slik fungerer det',
    step: 'Trinn',
    leadTimes: 'Leveringstider',
    tierHeader: 'Nivå',
    quantityHeader: 'Antall',
    workingDaysHeader: 'Virkedager',
    applications: 'Bruksområder',
    whyMicronsHub: 'Hvorfor Microns Hub',
    faq: 'Ofte stilte spørsmål',
    relatedServices: 'Relaterte tjenester',
  },
  hu: {
    capabilities: 'Képességek',
    materials: 'Anyagok',
    materialHeader: 'Anyag',
    gradeHeader: 'Minőség',
    propertiesHeader: 'Tulajdonságok',
    commonUsesHeader: 'Tipikus felhasználás',
    tolerances: 'Tűrések és specifikációk',
    specHeader: 'Jellemző',
    valueHeader: 'Érték',
    notesHeader: 'Megjegyzések',
    howItWorks: 'Hogyan működik',
    step: 'Lépés',
    leadTimes: 'Átfutási idők',
    tierHeader: 'Szint',
    quantityHeader: 'Mennyiség',
    workingDaysHeader: 'Munkanap',
    applications: 'Alkalmazások',
    whyMicronsHub: 'Miért Microns Hub',
    faq: 'Gyakran ismételt kérdések',
    relatedServices: 'Kapcsolódó szolgáltatások',
  },
  cs: {
    capabilities: 'Schopnosti',
    materials: 'Materiály',
    materialHeader: 'Materiál',
    gradeHeader: 'Jakost',
    propertiesHeader: 'Vlastnosti',
    commonUsesHeader: 'Typická použití',
    tolerances: 'Tolerance a specifikace',
    specHeader: 'Parametr',
    valueHeader: 'Hodnota',
    notesHeader: 'Poznámky',
    howItWorks: 'Jak to funguje',
    step: 'Krok',
    leadTimes: 'Dodací lhůty',
    tierHeader: 'Úroveň',
    quantityHeader: 'Množství',
    workingDaysHeader: 'Pracovní dny',
    applications: 'Aplikace',
    whyMicronsHub: 'Proč Microns Hub',
    faq: 'Často kladené otázky',
    relatedServices: 'Související služby',
  },
};

export function labelsFor(lang: Lang): ServicePageLabels {
  return SERVICE_PAGE_LABELS[lang] || EN;
}
