// Shapes of the Xometry scanner (Phase 5, unit X5) after parsing. Field names are the Python attribute names of
// xometry-bot (snake_case), so the golden vectors generated by the real Python code compare one to one.
//
// Rules
//   - Dates are ISO strings 'YYYY-MM-DD'; datetimes are the JSON form pydantic writes ('…Z' for UTC, '±HH:MM' for
//     another offset, no suffix for a naive value; six fraction digits only when the microseconds are not zero).
//   - raw is the offer object of the partner answer exactly as received (audit column xometry_offers.raw).

export interface Tag {
  id: number;
  name: string;
  context: string;
}

export interface PartFile {
  id: number | string | null;
  name: string;
  download_url: string | null;
  preview: string | null;
  large_url: string | null;
}

export interface JobInfo {
  public_comment: string | null;
  state: string | null;
}

export interface JobOfferPart {
  code: string | null;
  name: string | null;
  material: string | null;
  process_type: string | null;
  quantity: number | null;
  dimensions: string | null;
  weight_kg: number | null;
  volume_mm3: number | null;
  /** '' = no finish; anything else is a coating or finish text. */
  finish: string;
  production_remark: string | null;
  measurement_protocol_needed: boolean;
  samples_needed: boolean;
  tags: Tag[];
  files: PartFile[];
}

export interface Money {
  amount: number;
  currency: string;
}

export interface JobOffer {
  id: number | string;
  /** 'HJO-…', the dedupe key. */
  code: string;
  allow_autoaccept: boolean | null;
  allow_counteroffer_from: number | null;
  cost: Money | null;
  /** 'YYYY-MM-DD'. */
  leadtime: string | null;
  is_urgent: boolean;
  job_id: number | string | null;
  job: JobInfo | null;
  parts: JobOfferPart[];
  publication_start: string | null;
  publication_end: string | null;
  /** The offer object as received; never part of the parsed dump. */
  raw: Record<string, unknown>;
}

export interface ScanMetadata {
  has_more: boolean;
  limit: number;
  offset: number;
  total_count: number | null;
}

export interface ScanPage {
  metadata: ScanMetadata;
  offers: JobOffer[];
}

export interface PartFileRef {
  name: string;
  downloadUrl: string | null;
}

/** One xometry_offers row as the scanner writes it: the 30 insert columns of xometry-bot/xometry_bot/db.py. */
export interface OfferRow {
  code: string;
  offer_id: string;
  is_urgent: boolean;
  process_type: string | null;
  material: string | null;
  quantity: number | null;
  dimensions: string | null;
  weight_kg: number | null;
  volume_mm3: number | null;
  tags: string[];
  tolerance: string | null;
  roughness: string | null;
  finish: string | null;
  threads_present: boolean | null;
  inspection_needed: boolean;
  excluded_reason: string | null;
  part_files: PartFileRef[];
  local_files: string[];
  production_remark: string | null;
  partner_cost: number | null;
  allow_counter_from: number | null;
  buyer_price: number | null;
  buyer_quote_id: string | null;
  suggested_price: number | null;
  xo_leadtime: string | null;
  publication_end: string | null;
  suggested_leadtime: string | null;
  status: string;
  flags: string[];
  raw: Record<string, unknown>;
}

export interface Preset {
  name: string;
  include: ReadonlySet<number>;
  exclude: ReadonlySet<number>;
}

export interface Spec {
  tolerance: string | null;
  roughness: string | null;
  finish: string | null;
  inspection_needed: boolean;
  flags: string[];
}

export interface SecondaryOpHit {
  op_name: string;
  source: 'tag' | 'finish';
}

/** A partner payload that does not match the expected shape; locs as pydantic reports them (aliases, indexes as
 *  strings), in field order. */
export class XometrySchemaError extends Error {
  readonly locs: string[][];
  constructor(locs: string[][]) {
    super(`partner payload does not match the schema at ${locs.map((l) => l.join('.') || '<root>').join(', ')}`.slice(0, 500));
    this.name = 'XometrySchemaError';
    this.locs = locs;
  }
}
