// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfjrtmtaitwzggzpkhxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmanJ0bXRhaXR3emdnenBraHhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MjE3MDAsImV4cCI6MjA2MDQ5NzcwMH0.AwPwSd9wJBijIhQd6ftI7pPdRfTkJh2pi2isFnoywNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);