/**
 * Complete sitemap — serves the pre-generated sitemap from Supabase Storage.
 * Accessible at: https://www.micronshub.eu/sitemap-complete.xml
 *
 * The sitemap is generated by the Supabase Edge Function "generate-sitemap"
 * (triggered from the dashboard) and stored in Supabase Storage bucket "sitemaps".
 * This handler simply fetches and serves that pre-generated file,
 * avoiding serverless function timeouts from dynamic XML generation.
 *
 * Fallback: if Supabase Storage is unavailable, delegates to the
 * programmatic sitemap.xml handler.
 */

const STORAGE_URL = 'https://cfjrtmtaitwzggzpkhxi.supabase.co/storage/v1/object/public/sitemaps/sitemap-complete.xml';

export default async function handler(req, res) {
  res.setHeader('Content-Type', 'application/xml; charset=utf-8');
  res.setHeader('Cache-Control', 'public, max-age=3600, s-maxage=3600');

  try {
    // Fetch the pre-generated sitemap from Supabase Storage
    const response = await fetch(STORAGE_URL);

    if (!response.ok) {
      throw new Error('Supabase Storage returned ' + response.status);
    }

    const xml = await response.text();

    // Validate it looks like a sitemap (basic check)
    if (!xml || !xml.includes('<urlset') || xml.length < 100) {
      throw new Error('Sitemap from storage appears empty or invalid');
    }

    res.status(200).send(xml);
  } catch (error) {
    console.error('[sitemap-complete] Error fetching from storage:', error.message);

    // Fallback: delegate to the programmatic sitemap generator
    try {
      const { default: sitemapHandler } = await import('./sitemap.xml.js');
      return sitemapHandler(req, res);
    } catch (fallbackError) {
      console.error('[sitemap-complete] Fallback also failed:', fallbackError.message);
      res.status(500).send('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"/>');
    }
  }
}
