/**
 * Consolidated Sitemap API — single source of truth.
 *
 * /sitemap.xml (declared in robots.txt) is the canonical sitemap. The Vercel
 * rewrite routes it here; /sitemap-complete.xml now 301-redirects to
 * /sitemap.xml at the Vercel rewrite layer — no more two endpoints with
 * near-identical payloads.
 *
 * Content-page URLs (industries, our-work, about, contact, education,
 * legal-notice, privacy-policy, …) are pulled LIVE from content_pages instead
 * of a hardcoded array. Every time a new slug or language row is published,
 * the sitemap picks it up on the next regeneration. A regression guard logs
 * an error if the count of emitted content-page URLs drops below the count
 * of published rows in content_pages — that's how the previous 42-URL gap
 * went silent for months.
 *
 * Storage-first: on each request we try Supabase Storage's sitemap-complete
 * blob (regenerated by the generate-sitemap Edge Function on cron). Only if
 * Storage is unavailable do we build a fresh sitemap on the fly here.
 *
 * Other routes handled via ?type: index, lang.
 */

const SUPABASE_URL = 'https://cfjrtmtaitwzggzpkhxi.supabase.co';
const STORAGE_URL = SUPABASE_URL + '/storage/v1/object/public/sitemaps/sitemap-complete.xml';
const BASE_URL = 'https://www.micronshub.eu';

function escapeXml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function encodeSitemapUrl(url) {
  try {
    const urlObj = new URL(url);
    urlObj.pathname = urlObj.pathname
      .split('/')
      .map(segment => encodeURIComponent(decodeURIComponent(segment)))
      .join('/');
    return urlObj.toString();
  } catch {
    return encodeURI(url);
  }
}

const LANGUAGES = ['en', 'de', 'fr', 'es', 'it', 'nl', 'pl', 'pt', 'sv', 'da', 'fi', 'nb', 'hu', 'cs'];

const SLUGS = {
  en: { services: 'services', quote: 'quote', blog: 'blog', cnc: 'cnc-machining', sheetMetal: 'sheet-metal', printing: '3d-printing', injection: 'injection-molding', surface: 'surface-finishes', rapid: 'rapid-prototyping' },
  de: { services: 'dienstleistungen', quote: 'angebot', blog: 'blog', cnc: 'cnc-bearbeitung', sheetMetal: 'blechbearbeitung', printing: '3d-druck', injection: 'spritzguss', surface: 'oberflaechenveredelung', rapid: 'rapid-prototyping' },
  fr: { services: 'services', quote: 'devis', blog: 'blog', cnc: 'usinage-cnc', sheetMetal: 'tolerie', printing: 'impression-3d', injection: 'injection-plastique', surface: 'finition-surface', rapid: 'prototypage-rapide' },
  es: { services: 'servicios', quote: 'cotizacion', blog: 'blog', cnc: 'mecanizado-cnc', sheetMetal: 'chapa-metalica', printing: 'impresion-3d', injection: 'moldeo-por-inyeccion', surface: 'acabados-superficie', rapid: 'prototipado-rapido' },
  it: { services: 'servizi', quote: 'preventivo', blog: 'blog', cnc: 'lavorazione-cnc', sheetMetal: 'lavorazione-lamiera', printing: 'stampa-3d', injection: 'stampaggio-iniezione', surface: 'finitura-superficie', rapid: 'prototipazione-rapida' },
  nl: { services: 'diensten', quote: 'offerte', blog: 'blog', cnc: 'cnc-bewerking', sheetMetal: 'plaatbewerking', printing: '3d-printen', injection: 'spuitgieten', surface: 'oppervlakteafwerking', rapid: 'rapid-prototyping' },
  pl: { services: 'uslugi', quote: 'wycena', blog: 'blog', cnc: 'obrobka-cnc', sheetMetal: 'obrobka-bluzy', printing: 'druk-3d', injection: 'wtrysk-tworzywa', surface: 'wykonczenie-powierzchni', rapid: 'szybkie-prototypowanie' },
  pt: { services: 'servicos', quote: 'orcamento', blog: 'blog', cnc: 'usinagem-cnc', sheetMetal: 'chapa-metalica', printing: 'impressao-3d', injection: 'moldagem-injecao', surface: 'acabamento-superficie', rapid: 'prototipagem-rapida' },
  sv: { services: 'tjanster', quote: 'offert', blog: 'blogg', cnc: 'cnc-bearbetning', sheetMetal: 'platbearbetning', printing: '3d-skrivning', injection: 'formsprutning', surface: 'ytbehandling', rapid: 'snabb-prototypering' },
  da: { services: 'tjenester', quote: 'tilbud', blog: 'blog', cnc: 'cnc-bearbejdning', sheetMetal: 'pladearbejde', printing: '3d-printing', injection: 'sprojtestobning', surface: 'overfladebehandling', rapid: 'hurtig-prototypering' },
  fi: { services: 'palvelut', quote: 'tarjous', blog: 'blogi', cnc: 'cnc-työstö', sheetMetal: 'levytyöstö', printing: '3d-tulostus', injection: 'ruiskupuristus', surface: 'pinnan-viimeistely', rapid: 'nopea-prototyyppaus' },
  nb: { services: 'tjenester', quote: 'tilbud', blog: 'blogg', cnc: 'cnc-bearbeiding', sheetMetal: 'platarbeid', printing: '3d-printing', injection: 'sproytestoping', surface: 'overflatebehandling', rapid: 'rask-prototyping' },
  hu: { services: 'szolgaltatasok', quote: 'ajanlat', blog: 'blog', cnc: 'cnc-megmunkalas', sheetMetal: 'lemezfeldolgozas', printing: '3d-nyomtas', injection: 'frccsnyomas', surface: 'feluletkezeles', rapid: 'gyors-prototipus' },
  cs: { services: 'sluzby', quote: 'nabidka', blog: 'blog', cnc: 'cnc-obrabeni', sheetMetal: 'obrabeni-plechu', printing: '3d-tisk', injection: 'vstrekovani', surface: 'uprava-povrchu', rapid: 'rychle-prototypovani' },
};

// Static pages that are NOT sourced from content_pages. Home is emitted as
// the bare /:lang/ root; the blog index gets a dedicated entry; service
// pages live in service_pages but share the same localized-slug map here
// because their URLs haven't changed. Keep this list minimal — any page
// that lives in content_pages MUST be added to content_pages and emitted
// by fetchContentPages() below, not here (that's how the previous 42-URL
// gap slipped past review).
const STATIC_PAGES = [
  { key: 'home', path: () => '', priority: '1.0', changefreq: 'weekly' },
  { key: 'services', path: (s) => '/' + s.services, priority: '0.9', changefreq: 'weekly' },
  { key: 'cnc', path: (s) => '/' + s.services + '/' + s.cnc, priority: '0.9', changefreq: 'weekly' },
  { key: 'sheetMetal', path: (s) => '/' + s.services + '/' + s.sheetMetal, priority: '0.9', changefreq: 'weekly' },
  { key: 'printing', path: (s) => '/' + s.services + '/' + s.printing, priority: '0.9', changefreq: 'weekly' },
  { key: 'injection', path: (s) => '/' + s.services + '/' + s.injection, priority: '0.9', changefreq: 'weekly' },
  { key: 'surface', path: (s) => '/' + s.services + '/' + s.surface, priority: '0.8', changefreq: 'weekly' },
  { key: 'rapid', path: (s) => '/' + s.services + '/' + s.rapid, priority: '0.8', changefreq: 'weekly' },
  { key: 'quote', path: (s) => '/' + s.quote, priority: '0.8', changefreq: 'weekly' },
  { key: 'quoteRequest', path: () => '/quote-request', priority: '0.7', changefreq: 'weekly' },
  { key: 'blog', path: (s) => '/' + s.blog, priority: '0.8', changefreq: 'daily' },
];

// Per-slug metadata for content_pages entries. Anything not listed here
// uses the default fallbacks below.
const CONTENT_PAGE_META = {
  'industries':     { priority: '0.8', changefreq: 'weekly' },
  'our-work':       { priority: '0.7', changefreq: 'monthly' },
  'about':          { priority: '0.7', changefreq: 'monthly' },
  'contact':        { priority: '0.7', changefreq: 'monthly' },
  'education':      { priority: '0.7', changefreq: 'monthly' },
  'legal-notice':   { priority: '0.4', changefreq: 'yearly' },
  'privacy-policy': { priority: '0.4', changefreq: 'yearly' },
};

function buildPageUrl(lang, page) {
  const s = SLUGS[lang];
  const pagePath = page.path(s);
  return encodeSitemapUrl(BASE_URL + '/' + lang + pagePath);
}

function buildStaticPageHreflang(page) {
  const links = LANGUAGES.map(lang => {
    const url = escapeXml(buildPageUrl(lang, page));
    return '    <xhtml:link rel="alternate" hreflang="' + lang + '" href="' + url + '"/>';
  });
  const englishUrl = escapeXml(buildPageUrl('en', page));
  links.push('    <xhtml:link rel="alternate" hreflang="x-default" href="' + englishUrl + '"/>');
  return links.join('\n');
}

function buildStaticUrlEntry(lang, page, today) {
  const loc = escapeXml(buildPageUrl(lang, page));
  // sitemaps.org XSD: <loc>/<lastmod>/<changefreq>/<priority> first, then
  // xhtml:link extensions. Reversing this trips GSC's strict validator.
  return '  <url>\n    <loc>' + loc + '</loc>\n    <lastmod>' + today + '</lastmod>\n    <changefreq>' + page.changefreq + '</changefreq>\n    <priority>' + page.priority + '</priority>\n' + buildStaticPageHreflang(page) + '\n  </url>';
}

function buildContentPageUrl(lang, row) {
  const segment = row.localized_slug || row.slug;
  return encodeSitemapUrl(BASE_URL + '/' + lang + '/' + segment);
}

function buildContentPageHreflang(slugGroup) {
  const links = [];
  for (const lang of LANGUAGES) {
    const row = slugGroup.get(lang);
    if (!row) continue;
    const url = escapeXml(buildContentPageUrl(lang, row));
    links.push('    <xhtml:link rel="alternate" hreflang="' + lang + '" href="' + url + '"/>');
  }
  const enRow = slugGroup.get('en') || slugGroup.values().next().value;
  if (enRow) {
    const defaultLang = slugGroup.has('en') ? 'en' : [...slugGroup.keys()][0];
    const url = escapeXml(buildContentPageUrl(defaultLang, enRow));
    links.push('    <xhtml:link rel="alternate" hreflang="x-default" href="' + url + '"/>');
  }
  return links.join('\n');
}

function buildContentPageUrlEntry(lang, row, slugGroup, today) {
  const loc = escapeXml(buildContentPageUrl(lang, row));
  const meta = CONTENT_PAGE_META[row.slug] || { priority: '0.6', changefreq: 'monthly' };
  const lastmod = row.updated_at ? String(row.updated_at).split('T')[0] : today;
  return '  <url>\n    <loc>' + loc + '</loc>\n    <lastmod>' + lastmod + '</lastmod>\n    <changefreq>' + meta.changefreq + '</changefreq>\n    <priority>' + meta.priority + '</priority>\n' + buildContentPageHreflang(slugGroup) + '\n  </url>';
}

function buildBlogHreflang(article, siblings) {
  const links = siblings.map(sibling => {
    const lang = (sibling.language || 'en').trim().toLowerCase();
    const blogSlug = SLUGS[lang]?.blog || 'blog';
    const url = escapeXml(encodeSitemapUrl(BASE_URL + '/' + lang + '/' + blogSlug + '/' + sibling.slug));
    return '    <xhtml:link rel="alternate" hreflang="' + lang + '" href="' + url + '"/>';
  });
  const englishSibling = siblings.find(s => (s.language || '').trim().toLowerCase() === 'en');
  if (englishSibling) {
    const url = escapeXml(encodeSitemapUrl(BASE_URL + '/en/' + SLUGS.en.blog + '/' + englishSibling.slug));
    links.push('    <xhtml:link rel="alternate" hreflang="x-default" href="' + url + '"/>');
  }
  return links.join('\n');
}

function buildBlogUrlEntry(article, siblings, today) {
  const lang = (article.language || 'en').trim().toLowerCase();
  const blogSlug = SLUGS[lang]?.blog || 'blog';
  const loc = escapeXml(encodeSitemapUrl(BASE_URL + '/' + lang + '/' + blogSlug + '/' + article.slug));
  const lastmod = (article.updated_at || article.created_at || today).split('T')[0];
  const hreflang = siblings.length > 1 ? '\n' + buildBlogHreflang(article, siblings) : '';
  return '  <url>\n    <loc>' + loc + '</loc>\n    <lastmod>' + lastmod + '</lastmod>\n    <changefreq>weekly</changefreq>\n    <priority>0.6</priority>' + hreflang + '\n  </url>';
}

async function fetchBlogArticles() {
  const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';
  if (!SUPABASE_ANON_KEY) {
    console.warn('[sitemap] SUPABASE_ANON_KEY not set');
    return [];
  }
  try {
    const response = await fetch(
      SUPABASE_URL + '/rest/v1/articles?select=slug,language,updated_at,created_at,translation_id&status=eq.published&order=created_at.desc',
      { headers: { 'apikey': SUPABASE_ANON_KEY, 'Authorization': 'Bearer ' + SUPABASE_ANON_KEY } }
    );
    if (!response.ok) return [];
    const articles = await response.json();
    return Array.isArray(articles) ? articles : [];
  } catch (error) {
    console.error('[sitemap] Error fetching articles:', error);
    return [];
  }
}

async function fetchContentPages() {
  const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';
  if (!SUPABASE_ANON_KEY) {
    console.warn('[sitemap] SUPABASE_ANON_KEY not set');
    return [];
  }
  try {
    // Pull every published content_pages row in a single round trip. 'home'
    // is excluded because it's rendered as bare /:lang/ via STATIC_PAGES;
    // 'blog' is excluded because the blog INDEX has its own STATIC_PAGES
    // entry and individual blog articles come from fetchBlogArticles().
    const response = await fetch(
      SUPABASE_URL + '/rest/v1/content_pages?select=language,slug,localized_slug,updated_at&status=eq.published&slug=not.in.(home,blog)&order=slug,language',
      { headers: { 'apikey': SUPABASE_ANON_KEY, 'Authorization': 'Bearer ' + SUPABASE_ANON_KEY } }
    );
    if (!response.ok) return [];
    const rows = await response.json();
    return Array.isArray(rows) ? rows : [];
  } catch (error) {
    console.error('[sitemap] Error fetching content_pages:', error);
    return [];
  }
}

function groupContentPagesByCanonicalSlug(rows) {
  const groups = new Map();
  for (const row of rows) {
    const lang = (row.language || '').trim().toLowerCase();
    if (!LANGUAGES.includes(lang)) continue;
    if (!groups.has(row.slug)) groups.set(row.slug, new Map());
    groups.get(row.slug).set(lang, row);
  }
  return groups;
}

// ─── Main sitemap (with hreflang, blog entries, storage fallback) ───
async function handleMain(req, res) {
  try {
    const storageResponse = await fetch(STORAGE_URL);
    if (storageResponse.ok) {
      const xml = await storageResponse.text();
      if (xml && xml.includes('<urlset') && xml.length > 100) {
        return res.status(200).send(xml);
      }
    }
  } catch (e) {
    console.warn('[sitemap] Storage fetch failed, falling back to dynamic generation:', e.message);
  }

  try {
    const today = new Date().toISOString().split('T')[0];

    // Fetch blog + content_pages in parallel so cold-start cost is one RTT.
    const [articles, contentPages] = await Promise.all([
      fetchBlogArticles(),
      fetchContentPages(),
    ]);

    const staticEntries = [];
    for (const page of STATIC_PAGES) {
      for (const lang of LANGUAGES) {
        staticEntries.push(buildStaticUrlEntry(lang, page, today));
      }
    }

    const contentGroups = groupContentPagesByCanonicalSlug(contentPages);
    const contentEntries = [];
    let contentUrlCount = 0;
    for (const [, slugGroup] of contentGroups) {
      for (const [lang, row] of slugGroup) {
        contentEntries.push(buildContentPageUrlEntry(lang, row, slugGroup, today));
        contentUrlCount++;
      }
    }

    // Regression guard: every published content_pages row must appear in the
    // sitemap. If emission count falls below DB count, log a loud error so
    // this gap doesn't go silent for another three months.
    if (contentUrlCount < contentPages.length) {
      console.error(
        '[sitemap] Regression guard tripped: emitted ' + contentUrlCount +
        ' content-page URLs but content_pages has ' + contentPages.length +
        ' published rows. Missing rows likely have an unsupported language.'
      );
    }

    const translationGroups = new Map();
    const orphanArticles = [];
    for (const article of articles) {
      const normalizedLang = (article.language || '').trim().toLowerCase();
      if (!LANGUAGES.includes(normalizedLang)) continue;
      if (article.translation_id) {
        if (!translationGroups.has(article.translation_id)) translationGroups.set(article.translation_id, []);
        translationGroups.get(article.translation_id).push(article);
      } else {
        orphanArticles.push(article);
      }
    }

    const blogEntries = [];
    for (const [, siblings] of translationGroups) {
      for (const article of siblings) blogEntries.push(buildBlogUrlEntry(article, siblings, today));
    }
    for (const article of orphanArticles) blogEntries.push(buildBlogUrlEntry(article, [article], today));

    const xml = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n' +
      staticEntries.join('\n') + '\n' +
      contentEntries.join('\n') + '\n' +
      blogEntries.join('\n') + '\n</urlset>';
    res.status(200).send(xml);
  } catch (error) {
    console.error('[sitemap] Error generating sitemap:', error);
    res.status(500).send('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"/>');
  }
}

// ─── Sitemap index ───
async function handleIndex(req, res) {
  try {
    const sitemapUrl = SUPABASE_URL + '/storage/v1/object/public/sitemaps/sitemap-index.xml';
    const response = await fetch(sitemapUrl, { headers: { 'Accept': 'application/xml' } });
    if (!response.ok) {
      console.error('Failed to fetch sitemap-index: ' + response.status + ' ' + response.statusText);
      return res.status(200).send('<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n</sitemapindex>');
    }
    const xml = await response.text();
    res.status(200).send(xml);
  } catch (error) {
    console.error('Error serving sitemap-index:', error);
    res.status(200).send('<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n</sitemapindex>');
  }
}

// ─── Language-specific sitemap ───
async function handleLang(req, res) {
  const url = req.url || '';
  const match = url.match(/lang=([a-z]{2})/i);
  const lang = match ? match[1].toLowerCase() : 'en';

  if (!LANGUAGES.includes(lang)) {
    return res.status(404).send('Sitemap not found');
  }

  try {
    const sitemapUrl = SUPABASE_URL + '/storage/v1/object/public/sitemaps/sitemap-' + lang + '.xml';
    const response = await fetch(sitemapUrl, { headers: { 'Accept': 'application/xml' } });
    if (!response.ok) {
      console.error('Failed to fetch sitemap-' + lang + ': ' + response.status + ' ' + response.statusText);
      return res.status(404).send('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n</urlset>');
    }
    const xml = await response.text();
    res.status(200).send(xml);
  } catch (error) {
    console.error('Error serving sitemap-' + lang + ':', error);
    res.status(404).send('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n</urlset>');
  }
}

// ─── Sitemap-index pointing at /sitemap-complete.xml ────────────────────────
// /sitemap.xml is served as a tiny <sitemapindex> that references the full
// urlset at /sitemap-complete.xml. Why we shape it this way:
//
//   • GSC has been holding a stale "could not be read" verdict on /sitemap.xml
//     even though every wire-level probe shows it serves byte-identical XML
//     to /sitemap-complete.xml (which IS accepted). Returning a different
//     XML root element (`<sitemapindex>` instead of `<urlset>`) gives GSC's
//     parser a freshly-shaped document to validate, which in practice clears
//     the kind of submission-database error that survives manual re-submits.
//
//   • Sitemap-protocol-correct: an index that lists `/sitemap-complete.xml`
//     is exactly how google.com/webmasters/answer/183668 says to publish
//     multi-file or future-splittable sitemaps. The index → urlset chain is
//     resolved by every crawler.
//
//   • robots.txt continues advertising /sitemap.xml; Googlebot follows the
//     index to /sitemap-complete.xml on its own.
//
//   • /sitemap-complete.xml is unchanged — still served by handleMain as the
//     full urlset; existing GSC submissions for it stay valid.
function handleMainIndex(_req, res) {
  const today = new Date().toISOString().split('T')[0];
  const completeUrl = encodeSitemapUrl(BASE_URL + '/sitemap-complete.xml');
  const xml =
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
    '  <sitemap>\n' +
    '    <loc>' + escapeXml(completeUrl) + '</loc>\n' +
    '    <lastmod>' + today + '</lastmod>\n' +
    '  </sitemap>\n' +
    '</sitemapindex>\n';
  res.status(200).send(xml);
}

export default async function handler(req, res) {
  res.setHeader('Content-Type', 'application/xml; charset=utf-8');
  res.setHeader('Cache-Control', 'public, max-age=3600, s-maxage=3600');
  // Tell intermediaries the response varies by Accept-Encoding so CDN
  // caches don't mix gzip/br/identity bodies.
  res.setHeader('Vary', 'Accept-Encoding');

  const urlObj = new URL(req.url, 'http://localhost');
  const type = urlObj.searchParams.get('type');

  // Routing summary (vercel.json rewrites):
  //   /sitemap.xml          → ?type=main-index → handleMainIndex — sitemapindex pointing to /sitemap-complete.xml
  //   /sitemap-complete.xml → no query → handleMain — full urlset
  //   /sitemap-index.xml    → ?type=index      → legacy storage-backed index
  //   /sitemap-:lang.xml    → ?type=lang       → per-language storage blob
  // /sitemap.xml serves a tiny <sitemapindex> pointing to /sitemap-complete.xml
  if (type === 'main-index') return handleMainIndex(req, res);
  if (type === 'index') return handleIndex(req, res);
  if (type === 'lang') return handleLang(req, res);
  return handleMain(req, res);
}
